/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  javax.servlet.ServletException
 *  javax.servlet.annotation.WebServlet
 *  javax.servlet.http.HttpServletRequest
 *  javax.servlet.http.HttpServletResponse
 */
package com.iassets.biomedical.servlet.joborder;

import com.iassets.biomedical.entity.BioHospitalDevice;
import com.iassets.biomedical.entity.BioLookupJobOrderPriority;
import com.iassets.biomedical.entity.BioLookupJobOrderType;
import com.iassets.biomedical.servlet.BioBasicServlet;
import com.iassets.common.entity.CommonEmployee;
import com.iassets.common.util.Enums;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet(value={"/bio/JobOrderOpenDisplay"})
public class JobOrderOpenDisplayServlet
extends BioBasicServlet {
    private static final long serialVersionUID = 1L;

    public void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        request.setAttribute("jobOrderTypes", (Object)this.bioDBQueryManager.findAll(BioLookupJobOrderType.class));
        request.setAttribute("jobOrderPriorities", (Object)this.bioDBQueryManager.findAll(BioLookupJobOrderPriority.class));
        int siteId = this.getSessionSiteId(request);
        request.setAttribute("autoGeneratedJobOrderNo", (Object)(this.getSessionSite(request).getUserNameSpace().toUpperCase() + "-" + this.generateNewJobOrderNo(siteId)));
        request.setAttribute("responsibleEngs", this.bioDBQueryManager.getEmployees(siteId, new Enums.USER_TYPE[]{Enums.USER_TYPE.BIOMEDICAL_SITE_MANGER, Enums.USER_TYPE.BIOMEDICAL_ENGINEER, Enums.USER_TYPE.BIOMEDICAL_TECHNICIAN, Enums.USER_TYPE.BIOMEDICAL_CHEMIST}, false));
        CommonEmployee hospDepHead = ((BioHospitalDevice)request.getAttribute("deviceInfoObj")).getHospitalDepartment().getDepartmentHead();
        request.setAttribute("hospDepHead", (Object)hospDepHead);
        this.forward(request, response, "/bio/joborder/JobOrderOpen.jsp");
    }

    private String generateNewJobOrderNo(int siteId) {
        Date now = new Date();
        String yy = new SimpleDateFormat("yy").format(now);
        String mm = new SimpleDateFormat("MM").format(now);
        long serial = this.bioDBQueryManager.getJobOrderCount(siteId, Integer.parseInt(mm), Integer.parseInt("20" + yy)) + 1L;
        return "" + (Long.parseLong(yy + mm) * 10000L + serial);
    }
}
