///*
// * Decompiled with CFR 0.152.
// */
//package com.iassets.common.util;
//
//import com.iassets.common.util.LocalizationManager;
//
//public static enum Enums.REPORT_TITLE {
//    PROGRESS_BILL_PPM("common.util.Enums.REPORT_TITLE.PROGRESS_BILL_PPM"),
//    PROGRESS_BILL_SPARE_PARTS("common.util.Enums.REPORT_TITLE.PROGRESS_BILL_SPARE_PARTS"),
//    ONSITE_OPERATING_COMPANY_LABORERS("common.util.Enums.REPORT_TITLE.ONSITE_OPERATING_COMPANY_LABORERS"),
//    HOSPITAL_DEVICES("common.util.Enums.REPORT_TITLE.HOSPITAL_DEVICES"),
//    HOSPITAL_DEVICES_STATUS("common.util.Enums.REPORT_TITLE.HOSPITAL_DEVICES_STATUS"),
//    DEVICES_UNDER_MAINTENANCE("common.util.Enums.REPORT_TITLE.DEVICES_UNDER_MAINTENANCE"),
//    DEVICE_HISTORY("common.util.Enums.REPORT_TITLE.DEVICE_HISTORY"),
//    DEVICE_ACCESSORIES("common.util.Enums.REPORT_TITLE.DEVICE_ACCESSORIES"),
//    DEVICE_BY_WARRANTY_EXPIRE("common.util.Enums.REPORT_TITLE.DEVICE_BY_WARRANTY_EXPIRE"),
//    PPM_TABLE("common.util.Enums.REPORT_TITLE.PPM_TABLE"),
//    PPM_TABLE_WITHIN_ALL("common.util.Enums.REPORT_TITLE.PPM_TABLE_ALL"),
//    PPM_TABLE_ALL("common.util.Enums.REPORT_TITLE.PPM_TABLE_ALL"),
//    PPM_TABLE_WITHIN_WARRANTY("common.util.Enums.REPORT_TITLE.PPM_TABLE_WITHIN_WARRANTY"),
//    PPM_TABLE_OUTSIDE_WARRANTY("common.util.Enums.REPORT_TITLE.PPM_TABLE_OUTSIDE_WARRANTY"),
//    PPM_NOT_RECORDED_VISITS("common.util.Enums.REPORT_TITLE.PPM_NOT_RECORDED_VISITS"),
//    DEVICES_NEED_PPM_VISIT("common.util.Enums.REPORT_TITLE.DEVICES_NEED_PPM_VISIT"),
//    PPM_ATTACHED_FILES("common.util.Enums.REPORT_TITLE.PPM_ATTACHED_FILES"),
//    DEVICES_NOT_IN_CONTRACT("common.util.Enums.REPORT_TITLE.DEVICES_NOT_IN_CONTRACT"),
//    DEVICES_FROM_OTHER_SITE("common.util.Enums.REPORT_TITLE.DEVICES_FROM_OTHER_SITE"),
//    TRANSFERRED_DEVICES("common.util.Enums.REPORT_TITLE.TRANSFERRED_DEVICES"),
//    SCRAPPED_DEVICES("common.util.Enums.REPORT_TITLE.SCRAPPED_DEVICES"),
//    NOT_HAPPENED_PPM_VISITS("common.util.Enums.REPORT_TITLE.NOT_HAPPENED_PPM_VISITS"),
//    JOB_ORDER_CANCELLED("common.util.Enums.REPORT_TITLE.JOB_ORDER_CANCELLED"),
//    JOB_ORDER_CLOSED("common.util.Enums.REPORT_TITLE.JOB_ORDER_CLOSED"),
//    LATE_JOB_ORDERS("common.util.Enums.REPORT_TITLE.LATE_JOB_ORDERS"),
//    LATE_JOB_ORDERS_WITHIN_WARRANTY("common.util.Enums.REPORT_TITLE.LATE_JOB_ORDERS_WITH_WARRANTY"),
//    LATE_JOB_ORDERS_OUTSIDE_WARRANTY("common.util.Enums.REPORT_TITLE.LATE_JOB_ORDERS_OUTSIDE_WARRANTY"),
//    OPENED_JOB_ORDERS("common.util.Enums.REPORT_TITLE.OPENED_JOB_ORDERS"),
//    OPENED_JOB_ORDERS_WITHIN_WARRANTY("common.util.Enums.REPORT_TITLE.OPENED_JOB_ORDERS_WITH_WARRANTY"),
//    OPENED_JOB_ORDERS_OUTSIDE_WARRANTY("common.util.Enums.REPORT_TITLE.OPENED_JOB_ORDERS_OUTSIDE_WARRANTY"),
//    SP_INVENTORY_CONTENT("common.util.Enums.REPORT_TITLE.SP_INVENTORY_CONTENT"),
//    SP_INVENTORY_CONTENT_UNDER_THRESHOLD("common.util.Enums.REPORT_TITLE.SP_INVENTORY_CONTENT_UNDER_THRESHOLD"),
//    DEVICE_DETAILS("common.util.Enums.REPORT_TITLE.DEVICE_DETAILS"),
//    BIO_MAINTENANCE_REQUEST_LIST("common.util.Enums.REPORT_TITLE.BIO_MAINTENANCE_REQUEST_LIST"),
//    GEN_MAINTENANCE_REQUEST_LIST("common.util.Enums.REPORT_TITLE.GEN_MAINTENANCE_REQUEST_LIST"),
//    BIO_DIRECTORATE_MONTHLY_MAINTENANCE_PERFORMANCE("common.util.Enums.REPORT_TITLE.BIO_DIRECTORATE_MONTHLY_MAINTENANCE_PERFORMANCE");
//
//    protected String reportTitleLiteralKey;
//
//    private Enums.REPORT_TITLE(String reportTitleLiteralKey) {
//        this.reportTitleLiteralKey = reportTitleLiteralKey;
//    }
//
//    public String getReportTitle(String langCode) {
//        return LocalizationManager.getLiteral(this.reportTitleLiteralKey, langCode);
//    }
//}
